apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: wordcount-spark
  namespace: default
spec:
  type: Python
  mode: cluster
  image: swr.cn-north-4.myhuaweicloud.com/<ORG>/spark:v3.4.1
  imagePullPolicy: Always
  mainApplicationFile: s3a://<BUCKET>/wordcount.py
  sparkVersion: "3.4.1"
  restartPolicy: OnFailure
  driver:
    cores: 1
    memory: "1g"
    labels:
      version: 3.4.1
    serviceAccount: spark
  executor:
    instances: 2
    cores: 1
    memory: "1g"
    labels:
      version: 3.4.1
  volumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-pvc
  hadoopConf:
    fs.s3a.access.key: "<AK>"
    fs.s3a.secret.key: "<SK>"
    fs.s3a.endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
    fs.s3a.path.style.access: "true"
